Fix markdown for .env section
Pycord-Development/guide pull request #227
Opened 2022-10-10 09:51 UTC by Elitesparkle

Due to consecutive markdown blocks not being rendered correctly inside lists (only when accessing the page from the Pycord Guide), I removed one of the two examples that are basically showing the same thing in the same place. In addition to that, I improved the explanation so that it is more clear for beginners.

2022-10-11 20:55 UTC, BobDotCom requested changes

2022-10-11 20:55 UTC, BobDotCom commented on docs/getting-started/creating-your-first-bot.mdx
> +5. Pass your token as parameter when rurnning the bot.
```suggestion
5. Pass your token as parameter when running the bot.
```

2022-10-11 20:55 UTC, BobDotCom commented on docs/getting-started/creating-your-first-bot.mdx
> +   dotenv.load_dotenv()
```suggestion
   import dotenv
   dotenv.load_dotenv()
```

2022-10-16 03:50 UTC, BobDotCom commented
Please fix merge conflicts

2022-10-16 08:39 UTC, Elitesparkle reviewed
Add missing import and fix typo

2022-10-16 17:27 UTC, Lulalaby approved these changes

2022-10-16 17:27 UTC, merged