docs: Document select types and select channel types
Pycord-Development/guide pull request #317
Opened 2023-05-03 20:51 UTC by aLEGEND21

## Summary

Documented select types and select channel types in the guide.

## Information

- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

2023-05-03 20:55 UTC, Lulalaby commented
Thank you in advance! We're gonna look at some point the next days over this pr

2023-05-04 15:04 UTC, plun1331 requested changes
Consider also mentioning the shortcut decorators: https://docs.pycord.dev/en/master/api/ui_kit.html#discord.ui.string_select and below

2023-05-04 15:04 UTC, plun1331 commented on docs/interactions/ui-components/dropdowns.mdx
> +:::
This is incorrect, `Select.values` will resolve the received values to their respective objects, as they are sent with the interaction when selected.
https://github.com/Pycord-Development/pycord/blob/master/discord/ui/select.py#L328
https://docs.pycord.dev/en/master/api/ui_kit.html#discord.ui.Select.values

2023-05-04 15:04 UTC, plun1331 commented on docs/interactions/ui-components/dropdowns.mdx
> +        await interaction.response.send_message(f"Hello, <@{select.values[0]}>")
```suggestion
        await interaction.response.send_message(f"Hello, {select.values[0].mention}")
```

2023-05-04 15:04 UTC, plun1331 commented on docs/interactions/ui-components/dropdowns.mdx
> +        await interaction.response.send_message(f"You selected <#{select.values[0]}>")
```suggestion
        await interaction.response.send_message(f"You selected {select.values[0].mention}")
```

2023-05-04 15:07 UTC, plun1331 commented on docs/interactions/ui-components/dropdowns.mdx
>  -   `options`\*: A list of [`discord.SelectOption`](https://docs.pycord.dev/en/stable/api/data_classes.html#discord.SelectOption) values. These are the options that can be selected in this menu.
Can you make this not required as well kthx

2023-05-05 18:08 UTC, plun1331 approved these changes

2023-05-05 18:10 UTC, Lulalaby approved these changes

2023-05-05 18:10 UTC, merged